### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by talmo** [rly/ndx-pose#22]
As more packages in the ecosystem begin to adopt and support NWB for behavioral data, it'd be great to make the packaging and dependency situation a bit more developer/integration friendly.

A conda package (ideally on conda-forge) would be a great way to achieve this. Some relevant discussions:

https://github.com/talmolab/sleap-io/issues/73

https://github.com/neuroinformatics-unit/movement/issues/14

**Comment by niksirbi** [comment]
I agree it will be a great benefit for the pose-estimation ecosystem.

I think getting `ndx-pose` [released on `conda-forge`](https://conda-forge.org/docs/maintainer/adding_pkgs.html) should be straightforward, because:
1. The package is already on PyPI (complete with sdist and wheel), meaning we could use [`grayskull`](https://github.com/conda/grayskull) to streamline the staging process
2. As far as I can tell, the only absolute requirements are `pynwb` and `hdmf`, both of which are already available on `conda-forge`

**Comment by rly** [comment]
This makes sense. I'll get to it this week.

**Comment by rly** [comment]
`ndx-pose==0.1.1` is now available on conda-forge: https://github.com/conda-forge/ndx-pose-feedstock

I'm still working on version 0.2.0.

**Comment by niksirbi** [comment]
Fantastic! Thank you very much @rly !
